---
# These tasks install modules for test

- name: Install firefox xvfb
  yum: name={{ item }} state=present
  with_items:
   - firefox
   - Xvfb

- name: Install selenium
  shell: pip3.5 install selenium pyvirtualdisplay

- name: cpdriver
  copy:
    src: "{{local_code_path}}/www/geckodriver"
    dest: /usr/local/bin
#    owner: foo
#    group: foo
#    mode: 0644
